// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Archetype struct {
	ID                int32
	CreatedAt         string
	UpdatedAt         string
	Name              string
	PositionID        int32
	MaxStr            int32
	MaxAgi            int32
	MaxArm            int32
	MaxInt            int32
	MaxAcc            int32
	MaxTck            int32
	MaxSpe            int32
	MaxHnd            int32
	MaxPbl            int32
	MaxRbl            int32
	MaxKdi            int32
	MaxKac            int32
	MaxEnd            int32
	MinHeight         int32
	MaxHeight         int32
	MinWeight         int32
	MaxCreationWeight int32
	MaxWeight         int32
}

type Player struct {
	ID             int32
	CreatedAt      string
	UpdatedAt      string
	UserID         int32
	ArchetypeID    int32
	TeamID         int32
	FirstName      string
	LastName       string
	Strength       int32
	Agility        int32
	Arm            int32
	Intelligence   int32
	Accuracy       int32
	Tackling       int32
	Speed          int32
	Hands          int32
	PassBlocking   int32
	RunBlocking    int32
	KickDistance   int32
	KickAccuracy   int32
	Endurance      int32
	Height         int32
	Weight         int32
	Jersey         int32
	TotalTpe       int32
	AppliedTpe     int32
	RegressedTpe   int32
	ActiveStatus   string
	ContractYears  int32
	ContractSalary int32
	Money          int32
	Equipment1     string
	Equipment2     string
	Equipment3     string
}

type Position struct {
	ID           int32
	CreatedAt    string
	UpdatedAt    string
	Name         string
	Abbreviation string
	Side         string
}

type Team struct {
	ID        int32
	CreatedAt string
	UpdatedAt string
	City      string
	Mascot    string
	DdspfID   int32
}

type User struct {
	ID             int32
	CreatedAt      string
	UpdatedAt      string
	Username       string
	HashedPassword string
	IsAdmin        bool
	IsBod          bool
	IsSimmer       bool
	IsUpdater      bool
}
