// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: positions.sql

package database

import (
	"context"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (
    created_at, 
    updated_at, 
    name, 
    abbreviation,
    side
    )
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, name, abbreviation, side
`

type CreatePositionParams struct {
	Name         string
	Abbreviation string
	Side         string
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, createPosition, arg.Name, arg.Abbreviation, arg.Side)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Abbreviation,
		&i.Side,
	)
	return i, err
}
