// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: teams.sql

package database

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    created_at, 
    updated_at, 
    city, 
    mascot,
    ddspf_id
    )
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, city, mascot, ddspf_id
`

type CreateTeamParams struct {
	City    string
	Mascot  string
	DdspfID int32
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.City, arg.Mascot, arg.DdspfID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
		&i.Mascot,
		&i.DdspfID,
	)
	return i, err
}
