// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    created_at, 
    updated_at, 
    username, 
    hashed_password,
    is_admin,
    is_bod,
    is_simmer,
    is_updater
    )
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    false,
    false,
    false,
    false
)
RETURNING id, created_at, updated_at, username, hashed_password, is_admin, is_bod, is_simmer, is_updater
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsBod,
		&i.IsSimmer,
		&i.IsUpdater,
	)
	return i, err
}
